version: "3.8"

services:
  ecobnb_api:
    image: ecobnb_api
    container_name: ecobnb_api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: sh /app/start.sh
    depends_on:
      - ecobnb_db
      - ecobnb_cache
    ports:
      - 8081:8081
    environment:
      DATABASE_URI: mongodb://ecobnb_db:27017
      DATABASE_NAME: nestjs
      NODE_ENV: test
      MONGO_PORT: 27017
      PORT: 8081
      REDIS_HOST: ecobnb_cache
      REDIS_PORT: 6379
      CACHE_TTL: 3600
      DEFAULT_EMAIL: ikekatochukwu@gmail.com
      PAGE_LIMIT: 20
      MAIL_USER: ikekatochukwu@gmail.com
      MAIL_PASSWORD: xntzoshmhirpmwzw
      MAIL_FROM: noreply@example.com
      SECRET: qw34er5t656&&^**&2
      REQUEST_LIMIT: 3
  
  ecobnb_db:
    image: mongo
    container_name: ecobnb_db
    ports:
      - 27017:27017

  ecobnb_cache:
    image: redis:5-alpine
    container_name: ecobnb_cache
    ports:
      - 6379:6379
      