version: "3.8"

services:
      
  ecobnb_db:
    image: mongo
    container_name: ecobnb_db
    command: --replSet ecobnb_rs --bind_ip_all --port 27017
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/ 
  
  ecobnb_cache:
    image: redis:5-alpine
    container_name: ecobnb_cache
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - 6379:6379
    env_file:
      - .env